### ISSUE TITLE
Backticks missing on hostregex

### ISSUE THREAD

**Issue by mcchots** [DoTheEvo/Traefik-v2-examples#1]
Hi, firstly Thanks for this guide. It sorted out my HTTPS redirection that I've been struggling with for days.

on the hostregex rule in the HTTP to HTTPS redirection section, you are missing the backticks. It should be:
``- "traefik.http.routers.redirect-https.rule=hostregexp({`host:.+`})"``

**Comment by DoTheEvo** [comment]
thnx, they needed escaping in the explanation text...
