### ISSUE TITLE
Why i see a cloudflare certificate instead of lets encrypt?

### ISSUE THREAD

**Issue by TheBoneZone** [DoTheEvo/Traefik-v2-examples#2]
Hi,
i really appreciate your example. As a Treafik beginner it saved a lot of time.
Just one question. I do everything as described and it seemed to be ok. But if i access my site via https i see a certificate issued by cloudflare not by lets encrypt as expected?
At the cloudflare configuration i use the 'strict' ssl/tls option.

Any way to check if the lets encrypt certificate issued correct? I fear actually cloudflare is able 'read' the ssl trafik.

**Comment by lludlow** [comment]
If you are using traefik to only serve up https, then that is all cloudflare will see. When you have the "cloud" enabled (cloudflare proxy) you will see the cloudflare certificate externally.

you could test by editing your local hosts file to point to the IP that traefik is running on to bypass cloudflare

**Comment by TheBoneZone** [comment]
Thank you for triggering me again.
'Cloud' enabled was the right glue. I was not aware that i can disable the proxy at the cloudflare dns admin page. now i realised i have just to click on the cloud icon. %-) Without proxy service from cloudflare i see my lets encrypt certificate. 

Targed reached.
